version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./env/dev.env

  db:
    image: mysql:8.0.23
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./env/dev.env

volumes:
  wordpress:
  db:
