version: "3.7"

networks:
  homepage:
    external:
      name: homepage_default
  landingpages:
    external:
      name: landing_default

services:
  caddy:
    image: caddy:2.3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homepage
      - landingpages

volumes:
  caddy_data:
  caddy_config:
