name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: Docker Login
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_SERVER }}


  ########### ch3ck1nweb ######################
    - name: Install yarn CLI
      #uses: CultureHQ/actions-yarn@v1.0.1
      run: sudo apt-get update; sudo apt-get install yarn


    - name: Build app with yarn
      run: cd client-app; yarn install; yarn build; ls -la build; cd ..


    - name: Copy client-app build
      run: cd ch3ck1nweb; rm -Rf static; mkdir static; cp -R ../client-app/build/* ./static/; cd ..

    - name: ch3ck1nweb Build
      run: cd ch3ck1nweb; go build


    - name: ch3ck1nweb Docker Build & Push to registry
      run: cd ch3ck1nweb; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/ch3ck1nweb:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/ch3ck1nweb:${{ github.run_id }}
        
  
########### admin ######################
    - name: admin Build
      run: cd admin; go build


    - name: admin Docker Build & Push to registry
      run: cd admin; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/admin:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/admin:${{ github.run_id }}



########### authx ######################
    - name: authx Build
      run: cd authx; go build


    - name: authx Docker Build & Push to registry
      run: cd authx; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/authx:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/authx:${{ github.run_id }}



########### biz ######################
    - name: biz Build
      run: cd biz; go build


    - name: biz Docker Build & Push to registry
      run: cd biz; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/biz:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/biz:${{ github.run_id }}



########### checkins ######################
    - name: checkins Build
      run: cd checkins; go build


    - name: checkins Docker Build & Push to registry
      run: cd checkins; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/checkins:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/checkins:${{ github.run_id }}



########### pixi ######################
    - name: pixi Build
      run: cd pixi; go build


    - name: pixi Docker Build & Push to registry
      run: cd pixi; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/pixi:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/pixi:${{ github.run_id }}


########### albert ######################
    - name: albert service-gateway Build
      run: cd service-gateway; go build


    - name: albert service-gateway Docker Build & Push to registry
      run: cd service-gateway; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/service-gateway:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/service-gateway:${{ github.run_id }}


########### dbmate ######################
    - name: dbmate Docker Build & Push to registry
      run: cd dbmate; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/dbmate:${{ github.run_id }} .; docker push ${{ secrets.REGISTRY_SERVER }}/chckr/dbmate:${{ github.run_id }}


########### initial-acquire-biz ########################
    - name: initial-acquire-biz Build
      run: cd landing/initial-acquire-biz; go get -u github.com/gobuffalo/packr/packr; go get -u github.com/gobuffalo/packr; packr; packr build


    - name: initial-acquire-biz Docker Build & Push to registry
      run: cd landing/initial-acquire-biz; docker build -t ${{ secrets.REGISTRY_SERVER }}/chckr/landing-initial-acquire-biz:latest -t ${{ secrets.REGISTRY_SERVER }}/chckr/landing-initial-acquire-biz:${{ github.run_id }} .; docker push --all-tags ${{ secrets.REGISTRY_SERVER }}/chckr/landing-initial-acquire-biz:${{ github.run_id }}
