name: Deploy on Staging

on:
  workflow_run:
    workflows: ["Build and Push"]
    branches: [master]
    types: [completed]

jobs:
  on-success:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          STAGING_HOST: staging.chckr.de
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.STAGING_SSH_KEY }}"
          mkdir -pv ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -tv rsa $STAGING_HOST >> ~/.ssh/known_hosts
    
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Docker Login
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_SERVER }}
    
    - name: Deploy to staging
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: DOCKER_HOST="ssh://user@${STAGING_HOST}" ./docker/stacks/startAllStagingStacks.sh
